import { APIGatewayProxyEvent, APIGatewayProxyResult, Context } from 'aws-lambda';

/**
 * API Lambda - Public API endpoints
 * 
 * Handles:
 * - GET /player/{playerId} - Get player profile
 * - GET /player/{playerId}/matches - Get match history
 * - GET /player/{playerId}/insights - Get AI insights
 */

export const handler = async (
  event: APIGatewayProxyEvent,
  context: Context
): Promise<APIGatewayProxyResult> => {
  console.log('API Lambda invoked', { event, context });

  const { path, httpMethod, pathParameters } = event;
  const playerId = pathParameters?.playerId;

  try {
    // Route based on path
    if (path.includes('/insights')) {
      return await getInsights(playerId!);
    } else if (path.includes('/matches')) {
      return await getMatches(playerId!);
    } else {
      return await getPlayer(playerId!);
    }
  } catch (error) {
    console.error('Error in API handler:', error);
    return {
      statusCode: 500,
      headers: corsHeaders(),
      body: JSON.stringify({
        error: 'Internal server error',
        message: error instanceof Error ? error.message : 'Unknown error',
      }),
    };
  }
};

async function getPlayer(playerId: string): Promise<APIGatewayProxyResult> {
  // TODO: Query DynamoDB players table
  // TODO: Return player profile + stats

  return {
    statusCode: 200,
    headers: corsHeaders(),
    body: JSON.stringify({
      playerId,
      message: 'Player endpoint - placeholder',
      note: 'Implement DynamoDB query here',
    }),
  };
}

async function getMatches(playerId: string): Promise<APIGatewayProxyResult> {
  // TODO: Query DynamoDB matches table
  // TODO: Return paginated match history

  return {
    statusCode: 200,
    headers: corsHeaders(),
    body: JSON.stringify({
      playerId,
      matches: [],
      message: 'Matches endpoint - placeholder',
    }),
  };
}

async function getInsights(playerId: string): Promise<APIGatewayProxyResult> {
  // TODO: Check cache (DynamoDB insights table)
  // TODO: If cached and fresh, return
  // TODO: If stale or missing, trigger AI Lambda
  // TODO: Return insights

  if (playerId === 'demo') {
    // Demo data for judges
    return {
      statusCode: 200,
      headers: corsHeaders(),
      body: JSON.stringify({
        playerId: 'demo',
        heroSummary: {
          narrative: 'This is a demo player with sample insights. Your actual insights will be generated by AI!',
          keyHighlights: ['Strong laning phase', 'Excellent vision control', 'Consistent performance'],
          growthAreas: ['Late-game decision making'],
        },
        coachingTips: [
          {
            title: 'Improve ward placement',
            description: 'Place more deep wards after 25 minutes',
            priority: 'high',
          },
        ],
        playstyleRadar: {
          laning: 85,
          teamfighting: 70,
          vision: 92,
          objectiveControl: 75,
          roaming: 68,
          consistency: 80,
          mechanics: 78,
          decisionMaking: 65,
        },
      }),
    };
  }

  return {
    statusCode: 200,
    headers: corsHeaders(),
    body: JSON.stringify({
      playerId,
      message: 'Insights endpoint - placeholder',
    }),
  };
}

function corsHeaders() {
  return {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type,Authorization',
  };
}
