"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.handler = void 0;
/**
 * API Lambda - Public API endpoints
 *
 * Handles:
 * - GET /player/{playerId} - Get player profile
 * - GET /player/{playerId}/matches - Get match history
 * - GET /player/{playerId}/insights - Get AI insights
 */
const handler = async (event, context) => {
    console.log('API Lambda invoked', { event, context });
    const { path, httpMethod, pathParameters } = event;
    const playerId = pathParameters?.playerId;
    try {
        // Route based on path
        if (path.includes('/insights')) {
            return await getInsights(playerId);
        }
        else if (path.includes('/matches')) {
            return await getMatches(playerId);
        }
        else {
            return await getPlayer(playerId);
        }
    }
    catch (error) {
        console.error('Error in API handler:', error);
        return {
            statusCode: 500,
            headers: corsHeaders(),
            body: JSON.stringify({
                error: 'Internal server error',
                message: error instanceof Error ? error.message : 'Unknown error',
            }),
        };
    }
};
exports.handler = handler;
async function getPlayer(playerId) {
    // TODO: Query DynamoDB players table
    // TODO: Return player profile + stats
    return {
        statusCode: 200,
        headers: corsHeaders(),
        body: JSON.stringify({
            playerId,
            message: 'Player endpoint - placeholder',
            note: 'Implement DynamoDB query here',
        }),
    };
}
async function getMatches(playerId) {
    // TODO: Query DynamoDB matches table
    // TODO: Return paginated match history
    return {
        statusCode: 200,
        headers: corsHeaders(),
        body: JSON.stringify({
            playerId,
            matches: [],
            message: 'Matches endpoint - placeholder',
        }),
    };
}
async function getInsights(playerId) {
    // TODO: Check cache (DynamoDB insights table)
    // TODO: If cached and fresh, return
    // TODO: If stale or missing, trigger AI Lambda
    // TODO: Return insights
    if (playerId === 'demo') {
        // Demo data for judges
        return {
            statusCode: 200,
            headers: corsHeaders(),
            body: JSON.stringify({
                playerId: 'demo',
                heroSummary: {
                    narrative: 'This is a demo player with sample insights. Your actual insights will be generated by AI!',
                    keyHighlights: ['Strong laning phase', 'Excellent vision control', 'Consistent performance'],
                    growthAreas: ['Late-game decision making'],
                },
                coachingTips: [
                    {
                        title: 'Improve ward placement',
                        description: 'Place more deep wards after 25 minutes',
                        priority: 'high',
                    },
                ],
                playstyleRadar: {
                    laning: 85,
                    teamfighting: 70,
                    vision: 92,
                    objectiveControl: 75,
                    roaming: 68,
                    consistency: 80,
                    mechanics: 78,
                    decisionMaking: 65,
                },
            }),
        };
    }
    return {
        statusCode: 200,
        headers: corsHeaders(),
        body: JSON.stringify({
            playerId,
            message: 'Insights endpoint - placeholder',
        }),
    };
}
function corsHeaders() {
    return {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type,Authorization',
    };
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFFQTs7Ozs7OztHQU9HO0FBRUksTUFBTSxPQUFPLEdBQUcsS0FBSyxFQUMxQixLQUEyQixFQUMzQixPQUFnQixFQUNnQixFQUFFO0lBQ2xDLE9BQU8sQ0FBQyxHQUFHLENBQUMsb0JBQW9CLEVBQUUsRUFBRSxLQUFLLEVBQUUsT0FBTyxFQUFFLENBQUMsQ0FBQztJQUV0RCxNQUFNLEVBQUUsSUFBSSxFQUFFLFVBQVUsRUFBRSxjQUFjLEVBQUUsR0FBRyxLQUFLLENBQUM7SUFDbkQsTUFBTSxRQUFRLEdBQUcsY0FBYyxFQUFFLFFBQVEsQ0FBQztJQUUxQyxJQUFJLENBQUM7UUFDSCxzQkFBc0I7UUFDdEIsSUFBSSxJQUFJLENBQUMsUUFBUSxDQUFDLFdBQVcsQ0FBQyxFQUFFLENBQUM7WUFDL0IsT0FBTyxNQUFNLFdBQVcsQ0FBQyxRQUFTLENBQUMsQ0FBQztRQUN0QyxDQUFDO2FBQU0sSUFBSSxJQUFJLENBQUMsUUFBUSxDQUFDLFVBQVUsQ0FBQyxFQUFFLENBQUM7WUFDckMsT0FBTyxNQUFNLFVBQVUsQ0FBQyxRQUFTLENBQUMsQ0FBQztRQUNyQyxDQUFDO2FBQU0sQ0FBQztZQUNOLE9BQU8sTUFBTSxTQUFTLENBQUMsUUFBUyxDQUFDLENBQUM7UUFDcEMsQ0FBQztJQUNILENBQUM7SUFBQyxPQUFPLEtBQUssRUFBRSxDQUFDO1FBQ2YsT0FBTyxDQUFDLEtBQUssQ0FBQyx1QkFBdUIsRUFBRSxLQUFLLENBQUMsQ0FBQztRQUM5QyxPQUFPO1lBQ0wsVUFBVSxFQUFFLEdBQUc7WUFDZixPQUFPLEVBQUUsV0FBVyxFQUFFO1lBQ3RCLElBQUksRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDO2dCQUNuQixLQUFLLEVBQUUsdUJBQXVCO2dCQUM5QixPQUFPLEVBQUUsS0FBSyxZQUFZLEtBQUssQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMsZUFBZTthQUNsRSxDQUFDO1NBQ0gsQ0FBQztJQUNKLENBQUM7QUFDSCxDQUFDLENBQUM7QUE3QlcsUUFBQSxPQUFPLFdBNkJsQjtBQUVGLEtBQUssVUFBVSxTQUFTLENBQUMsUUFBZ0I7SUFDdkMscUNBQXFDO0lBQ3JDLHNDQUFzQztJQUV0QyxPQUFPO1FBQ0wsVUFBVSxFQUFFLEdBQUc7UUFDZixPQUFPLEVBQUUsV0FBVyxFQUFFO1FBQ3RCLElBQUksRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDO1lBQ25CLFFBQVE7WUFDUixPQUFPLEVBQUUsK0JBQStCO1lBQ3hDLElBQUksRUFBRSwrQkFBK0I7U0FDdEMsQ0FBQztLQUNILENBQUM7QUFDSixDQUFDO0FBRUQsS0FBSyxVQUFVLFVBQVUsQ0FBQyxRQUFnQjtJQUN4QyxxQ0FBcUM7SUFDckMsdUNBQXVDO0lBRXZDLE9BQU87UUFDTCxVQUFVLEVBQUUsR0FBRztRQUNmLE9BQU8sRUFBRSxXQUFXLEVBQUU7UUFDdEIsSUFBSSxFQUFFLElBQUksQ0FBQyxTQUFTLENBQUM7WUFDbkIsUUFBUTtZQUNSLE9BQU8sRUFBRSxFQUFFO1lBQ1gsT0FBTyxFQUFFLGdDQUFnQztTQUMxQyxDQUFDO0tBQ0gsQ0FBQztBQUNKLENBQUM7QUFFRCxLQUFLLFVBQVUsV0FBVyxDQUFDLFFBQWdCO0lBQ3pDLDhDQUE4QztJQUM5QyxvQ0FBb0M7SUFDcEMsK0NBQStDO0lBQy9DLHdCQUF3QjtJQUV4QixJQUFJLFFBQVEsS0FBSyxNQUFNLEVBQUUsQ0FBQztRQUN4Qix1QkFBdUI7UUFDdkIsT0FBTztZQUNMLFVBQVUsRUFBRSxHQUFHO1lBQ2YsT0FBTyxFQUFFLFdBQVcsRUFBRTtZQUN0QixJQUFJLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQztnQkFDbkIsUUFBUSxFQUFFLE1BQU07Z0JBQ2hCLFdBQVcsRUFBRTtvQkFDWCxTQUFTLEVBQUUsMkZBQTJGO29CQUN0RyxhQUFhLEVBQUUsQ0FBQyxxQkFBcUIsRUFBRSwwQkFBMEIsRUFBRSx3QkFBd0IsQ0FBQztvQkFDNUYsV0FBVyxFQUFFLENBQUMsMkJBQTJCLENBQUM7aUJBQzNDO2dCQUNELFlBQVksRUFBRTtvQkFDWjt3QkFDRSxLQUFLLEVBQUUsd0JBQXdCO3dCQUMvQixXQUFXLEVBQUUsd0NBQXdDO3dCQUNyRCxRQUFRLEVBQUUsTUFBTTtxQkFDakI7aUJBQ0Y7Z0JBQ0QsY0FBYyxFQUFFO29CQUNkLE1BQU0sRUFBRSxFQUFFO29CQUNWLFlBQVksRUFBRSxFQUFFO29CQUNoQixNQUFNLEVBQUUsRUFBRTtvQkFDVixnQkFBZ0IsRUFBRSxFQUFFO29CQUNwQixPQUFPLEVBQUUsRUFBRTtvQkFDWCxXQUFXLEVBQUUsRUFBRTtvQkFDZixTQUFTLEVBQUUsRUFBRTtvQkFDYixjQUFjLEVBQUUsRUFBRTtpQkFDbkI7YUFDRixDQUFDO1NBQ0gsQ0FBQztJQUNKLENBQUM7SUFFRCxPQUFPO1FBQ0wsVUFBVSxFQUFFLEdBQUc7UUFDZixPQUFPLEVBQUUsV0FBVyxFQUFFO1FBQ3RCLElBQUksRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDO1lBQ25CLFFBQVE7WUFDUixPQUFPLEVBQUUsaUNBQWlDO1NBQzNDLENBQUM7S0FDSCxDQUFDO0FBQ0osQ0FBQztBQUVELFNBQVMsV0FBVztJQUNsQixPQUFPO1FBQ0wsY0FBYyxFQUFFLGtCQUFrQjtRQUNsQyw2QkFBNkIsRUFBRSxHQUFHO1FBQ2xDLDhCQUE4QixFQUFFLGtCQUFrQjtRQUNsRCw4QkFBOEIsRUFBRSw0QkFBNEI7S0FDN0QsQ0FBQztBQUNKLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBBUElHYXRld2F5UHJveHlFdmVudCwgQVBJR2F0ZXdheVByb3h5UmVzdWx0LCBDb250ZXh0IH0gZnJvbSAnYXdzLWxhbWJkYSc7XG5cbi8qKlxuICogQVBJIExhbWJkYSAtIFB1YmxpYyBBUEkgZW5kcG9pbnRzXG4gKiBcbiAqIEhhbmRsZXM6XG4gKiAtIEdFVCAvcGxheWVyL3twbGF5ZXJJZH0gLSBHZXQgcGxheWVyIHByb2ZpbGVcbiAqIC0gR0VUIC9wbGF5ZXIve3BsYXllcklkfS9tYXRjaGVzIC0gR2V0IG1hdGNoIGhpc3RvcnlcbiAqIC0gR0VUIC9wbGF5ZXIve3BsYXllcklkfS9pbnNpZ2h0cyAtIEdldCBBSSBpbnNpZ2h0c1xuICovXG5cbmV4cG9ydCBjb25zdCBoYW5kbGVyID0gYXN5bmMgKFxuICBldmVudDogQVBJR2F0ZXdheVByb3h5RXZlbnQsXG4gIGNvbnRleHQ6IENvbnRleHRcbik6IFByb21pc2U8QVBJR2F0ZXdheVByb3h5UmVzdWx0PiA9PiB7XG4gIGNvbnNvbGUubG9nKCdBUEkgTGFtYmRhIGludm9rZWQnLCB7IGV2ZW50LCBjb250ZXh0IH0pO1xuXG4gIGNvbnN0IHsgcGF0aCwgaHR0cE1ldGhvZCwgcGF0aFBhcmFtZXRlcnMgfSA9IGV2ZW50O1xuICBjb25zdCBwbGF5ZXJJZCA9IHBhdGhQYXJhbWV0ZXJzPy5wbGF5ZXJJZDtcblxuICB0cnkge1xuICAgIC8vIFJvdXRlIGJhc2VkIG9uIHBhdGhcbiAgICBpZiAocGF0aC5pbmNsdWRlcygnL2luc2lnaHRzJykpIHtcbiAgICAgIHJldHVybiBhd2FpdCBnZXRJbnNpZ2h0cyhwbGF5ZXJJZCEpO1xuICAgIH0gZWxzZSBpZiAocGF0aC5pbmNsdWRlcygnL21hdGNoZXMnKSkge1xuICAgICAgcmV0dXJuIGF3YWl0IGdldE1hdGNoZXMocGxheWVySWQhKTtcbiAgICB9IGVsc2Uge1xuICAgICAgcmV0dXJuIGF3YWl0IGdldFBsYXllcihwbGF5ZXJJZCEpO1xuICAgIH1cbiAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICBjb25zb2xlLmVycm9yKCdFcnJvciBpbiBBUEkgaGFuZGxlcjonLCBlcnJvcik7XG4gICAgcmV0dXJuIHtcbiAgICAgIHN0YXR1c0NvZGU6IDUwMCxcbiAgICAgIGhlYWRlcnM6IGNvcnNIZWFkZXJzKCksXG4gICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7XG4gICAgICAgIGVycm9yOiAnSW50ZXJuYWwgc2VydmVyIGVycm9yJyxcbiAgICAgICAgbWVzc2FnZTogZXJyb3IgaW5zdGFuY2VvZiBFcnJvciA/IGVycm9yLm1lc3NhZ2UgOiAnVW5rbm93biBlcnJvcicsXG4gICAgICB9KSxcbiAgICB9O1xuICB9XG59O1xuXG5hc3luYyBmdW5jdGlvbiBnZXRQbGF5ZXIocGxheWVySWQ6IHN0cmluZyk6IFByb21pc2U8QVBJR2F0ZXdheVByb3h5UmVzdWx0PiB7XG4gIC8vIFRPRE86IFF1ZXJ5IER5bmFtb0RCIHBsYXllcnMgdGFibGVcbiAgLy8gVE9ETzogUmV0dXJuIHBsYXllciBwcm9maWxlICsgc3RhdHNcblxuICByZXR1cm4ge1xuICAgIHN0YXR1c0NvZGU6IDIwMCxcbiAgICBoZWFkZXJzOiBjb3JzSGVhZGVycygpLFxuICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAgIHBsYXllcklkLFxuICAgICAgbWVzc2FnZTogJ1BsYXllciBlbmRwb2ludCAtIHBsYWNlaG9sZGVyJyxcbiAgICAgIG5vdGU6ICdJbXBsZW1lbnQgRHluYW1vREIgcXVlcnkgaGVyZScsXG4gICAgfSksXG4gIH07XG59XG5cbmFzeW5jIGZ1bmN0aW9uIGdldE1hdGNoZXMocGxheWVySWQ6IHN0cmluZyk6IFByb21pc2U8QVBJR2F0ZXdheVByb3h5UmVzdWx0PiB7XG4gIC8vIFRPRE86IFF1ZXJ5IER5bmFtb0RCIG1hdGNoZXMgdGFibGVcbiAgLy8gVE9ETzogUmV0dXJuIHBhZ2luYXRlZCBtYXRjaCBoaXN0b3J5XG5cbiAgcmV0dXJuIHtcbiAgICBzdGF0dXNDb2RlOiAyMDAsXG4gICAgaGVhZGVyczogY29yc0hlYWRlcnMoKSxcbiAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7XG4gICAgICBwbGF5ZXJJZCxcbiAgICAgIG1hdGNoZXM6IFtdLFxuICAgICAgbWVzc2FnZTogJ01hdGNoZXMgZW5kcG9pbnQgLSBwbGFjZWhvbGRlcicsXG4gICAgfSksXG4gIH07XG59XG5cbmFzeW5jIGZ1bmN0aW9uIGdldEluc2lnaHRzKHBsYXllcklkOiBzdHJpbmcpOiBQcm9taXNlPEFQSUdhdGV3YXlQcm94eVJlc3VsdD4ge1xuICAvLyBUT0RPOiBDaGVjayBjYWNoZSAoRHluYW1vREIgaW5zaWdodHMgdGFibGUpXG4gIC8vIFRPRE86IElmIGNhY2hlZCBhbmQgZnJlc2gsIHJldHVyblxuICAvLyBUT0RPOiBJZiBzdGFsZSBvciBtaXNzaW5nLCB0cmlnZ2VyIEFJIExhbWJkYVxuICAvLyBUT0RPOiBSZXR1cm4gaW5zaWdodHNcblxuICBpZiAocGxheWVySWQgPT09ICdkZW1vJykge1xuICAgIC8vIERlbW8gZGF0YSBmb3IganVkZ2VzXG4gICAgcmV0dXJuIHtcbiAgICAgIHN0YXR1c0NvZGU6IDIwMCxcbiAgICAgIGhlYWRlcnM6IGNvcnNIZWFkZXJzKCksXG4gICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7XG4gICAgICAgIHBsYXllcklkOiAnZGVtbycsXG4gICAgICAgIGhlcm9TdW1tYXJ5OiB7XG4gICAgICAgICAgbmFycmF0aXZlOiAnVGhpcyBpcyBhIGRlbW8gcGxheWVyIHdpdGggc2FtcGxlIGluc2lnaHRzLiBZb3VyIGFjdHVhbCBpbnNpZ2h0cyB3aWxsIGJlIGdlbmVyYXRlZCBieSBBSSEnLFxuICAgICAgICAgIGtleUhpZ2hsaWdodHM6IFsnU3Ryb25nIGxhbmluZyBwaGFzZScsICdFeGNlbGxlbnQgdmlzaW9uIGNvbnRyb2wnLCAnQ29uc2lzdGVudCBwZXJmb3JtYW5jZSddLFxuICAgICAgICAgIGdyb3d0aEFyZWFzOiBbJ0xhdGUtZ2FtZSBkZWNpc2lvbiBtYWtpbmcnXSxcbiAgICAgICAgfSxcbiAgICAgICAgY29hY2hpbmdUaXBzOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdGl0bGU6ICdJbXByb3ZlIHdhcmQgcGxhY2VtZW50JyxcbiAgICAgICAgICAgIGRlc2NyaXB0aW9uOiAnUGxhY2UgbW9yZSBkZWVwIHdhcmRzIGFmdGVyIDI1IG1pbnV0ZXMnLFxuICAgICAgICAgICAgcHJpb3JpdHk6ICdoaWdoJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgICBwbGF5c3R5bGVSYWRhcjoge1xuICAgICAgICAgIGxhbmluZzogODUsXG4gICAgICAgICAgdGVhbWZpZ2h0aW5nOiA3MCxcbiAgICAgICAgICB2aXNpb246IDkyLFxuICAgICAgICAgIG9iamVjdGl2ZUNvbnRyb2w6IDc1LFxuICAgICAgICAgIHJvYW1pbmc6IDY4LFxuICAgICAgICAgIGNvbnNpc3RlbmN5OiA4MCxcbiAgICAgICAgICBtZWNoYW5pY3M6IDc4LFxuICAgICAgICAgIGRlY2lzaW9uTWFraW5nOiA2NSxcbiAgICAgICAgfSxcbiAgICAgIH0pLFxuICAgIH07XG4gIH1cblxuICByZXR1cm4ge1xuICAgIHN0YXR1c0NvZGU6IDIwMCxcbiAgICBoZWFkZXJzOiBjb3JzSGVhZGVycygpLFxuICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAgIHBsYXllcklkLFxuICAgICAgbWVzc2FnZTogJ0luc2lnaHRzIGVuZHBvaW50IC0gcGxhY2Vob2xkZXInLFxuICAgIH0pLFxuICB9O1xufVxuXG5mdW5jdGlvbiBjb3JzSGVhZGVycygpIHtcbiAgcmV0dXJuIHtcbiAgICAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nLFxuICAgICdBY2Nlc3MtQ29udHJvbC1BbGxvdy1PcmlnaW4nOiAnKicsXG4gICAgJ0FjY2Vzcy1Db250cm9sLUFsbG93LU1ldGhvZHMnOiAnR0VULFBPU1QsT1BUSU9OUycsXG4gICAgJ0FjY2Vzcy1Db250cm9sLUFsbG93LUhlYWRlcnMnOiAnQ29udGVudC1UeXBlLEF1dGhvcml6YXRpb24nLFxuICB9O1xufVxuIl19